services:
  task-manager-api:
    build: .

    container_name: task_manager_api

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - ./data:/code/data

    restart: unless-stopped